project:
  type: website


website:
  title: "Maize Breeding and Genomics Lab"
  site-url: https://MuMaizeBreedingLab.github.io/
  favicon: images/icon.png
  
  navbar:
    right:
    - text: "About"
      href: about.qmd
    - text: "People"
      href: people.qmd
    - text: "Join Our Lab!"
      href: join.qmd
    - text: "Publications"
      href: publications.qmd

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: true
    toc-title: Contents



