project:
  type: website


website:
  title: "Maize Breeding and Genomics Lab"
  site-url: https://MuMaizeBreedingLab.github.io/
  navbar:
    right:
    - text: "About""
      href: about.qmd
    - text: "People"
      href: People.qmd
    - text: "Join Our Lab!"
      href: Join Us.qmd
    - text: "Publications"
      href: Publications.qmd

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true
    toc-title: Contents



