project:
  type: website


website:
  title: "Maize Breeding and Genomics Lab"
  site-url: https://MuMaizeBreedingLab.github.io/
  favicon: images/lab_logo.png
  
  navbar:
    logo: images/lab_logo.png
    right:
    - text: "About"
      href: about.qmd
    - text: "People"
      href: people.qmd
    - text: "Join Our Lab!"
      href: join.qmd
    - text: "Publications"
      href: publications.qmd
    - text: "Contact us"
      href: contact.qmd

format:
  html:
    mainfont: Roboto
    theme: custom.scss
    css: styles.css
    toc: true
    toc-title: Contents



